all: compile link run

compile:
	g++ -I"C:\\Users\\DELL\\SFML-2.6.2\\include" -c main.cpp

link:
	g++ main.o -o main -L"C:\\Users\\DELL\\SFML-2.6.2\\lib" -lsfml-graphics -lsfml-window -lsfml-system
run:
	.\main.exe

.PHONY: all run