# Compiler and Flags
CXX = g++ 
CXXFLAGS = -Iinclude -std=c++17 
LDFLAGS = -Llib -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio -lsfml-network

# Target Executable
TARGET = main.exe

# Object Files
OBJECTS = main2.o Colors.o  WindowManager.o GridInfo.o Grid.o Blocks.o Game.o Score.o Server.o Client.o PacketsMap.o

# Default Target
all: $(TARGET)

# Linking Step
$(TARGET): $(OBJECTS)
	$(CXX) -o $@ $(OBJECTS) $(LDFLAGS)

# Compilation Step
main.o: main2.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

PacketsMap.o: PacketsMap.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

Colors.o: Colors.cpp Colors.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

Server.o: Server.cpp Server.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

Client.o: Client.cpp Client.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

WindowManager.o: WindowManager.cpp WindowManager.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

GridInfo.o: GridInfo.cpp GridInfo.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

Grid.o: Grid.cpp Grid.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

Blocks.o: Blocks.cpp Blocks.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

Game.o: Game.cpp Game.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

Score.o: Score.cpp Score.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

# Run the Program
run: $(TARGET)
	.\$(TARGET)

go: clean all run

# Clean Build Files
clean:
	del /f $(OBJECTS) $(TARGET)

.PHONY: all run clean
