
#define PACKET_TYPE_START 1
#define PACKET_TYPE_GAMEOVER 2
#define PACKET_TYPE_FINISHGAME 3
#define PACKET_TYPE_DISCONNECT 4
#define PACKET_TYPE_GRID 5
#define PACKET_TYPE_SCORE 6
#define LOCAL_HOST "127.0.0.1"
#define IP_SERVER "172.20.10.3"
#define PORT_SERVER 12345
#define TIMEOUT_SERVER 30
